# https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-poetry
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  commands:
    - curl -sSL https://install.python-poetry.org | python3 -
    - $HOME/.local/bin/poetry install
    - $HOME/.local/bin/poetry run make docs
    - mkdir _readthedocs
    - mv docs/_build/html _readthedocs
