name: pytest

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  linter:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10']

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: '1.1.13'

    - name: prepare
      run: |
        poetry install
    - name: pytest
      run: |
        poetry run python -m pytest -v tests/python
